### ISSUE TITLE
Index file size differs between CPython and PyPy, although same number of found elements

### ISSUE THREAD

**Issue by ArneBachmann** [ArneBachmann/tagsplorer#56]

**Comment by ArneBachmann** [comment]
Problem occurs when reading PyPy-index with CPython3:
```
Traceback (most recent call last):
  File "tp.py", line 390, in <module>
    Main().parse()
  File "tp.py", line 382, in parse
    elif _.options.stats: _.stats()
  File "tp.py", line 311, in stats
    idx.load(indexFile)
  File "/home/ash/Desktop/svn/projects/tagsplorer/lib.py", line 341, in load
    c = pickle.loads(zlib.decompress(fd.read()) if _.compressed else fd.read())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```

**Comment by ArneBachmann** [comment]
U+00C3 | Ã | c3 83 | LATIN CAPITAL LETTER A WITH TILDE

**Comment by ArneBachmann** [comment]
Pypy:
Indexed 2446 folders with 2446 tags
13:47:33.032 INFO lib:<lambda>:10 | Wrote 17 config bytes
13:47:33.032 INFO lib:<lambda>:10 | Wrote 25829 index bytes (2446 entries and 12826 paths)

CPython:
Indexed 2446 folders with 2446 tags
13:48:09.673 INFO lib:store:106 | Wrote 17 config bytes
13:48:09.673 INFO lib:store:209 | Wrote 26583 index bytes (2446 entries and 12827 paths)

**Comment by ArneBachmann** [comment]
Yet both seem to be compatible and the pickle version is fixed in the code, so we can close this.
